INSERT INTO category
VALUES (1, 'Tehisintellekti ja masinõppe alused'),
       (2, 'Tarkvaratehnika'),
       (3, 'Tõenäosusteooria ja matemaatiline statistika'),
       (4, 'Kasutajaliidesed'),
       (5, 'Andmebaasid I'),
       (6, 'Arvutid'),
       (7, 'Küberturbe alused'),
       (8, 'Operatsioonisüsteemid ja nende haldamine'),
       (9, 'Sissejuhatus infotehnoloogiasse'),
       (10, 'Arvutivõrgud'),
       (11, 'Diskreetne matemaatika I'),
       (12, 'Diskreetne matemaatika II'),
       (13, 'Kõrgem matemaatika I'),
       (14, 'Infosüsteemide arendus Javas'),
       (15, 'Programmeerimise algkursus'),
       (16, 'Programmeerimise põhikursus'),
       (17, 'Algortimid ja andmestruktuurid'),
       (18, 'Robotite programmeerimine'),
       (19, 'Veebirakendused');